sudo: required

services:
  - docker

language: bash

node_js:
  - 8

notifications:
  email: false

branches:
  only:
    - master

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker-compose pull
  - docker-compose up -d elasticsearch
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200

script:
  - docker-compose run --rm web npm run test

after_success:
  - docker push stono/asksarge
