sudo: required

services:
  - docker

language: bash

node_js:
  - 8

notifications:
  email: false

branches:
  only:
    - master

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker-compose pull
  - sleep 5

script:
  - docker-compose run --rm web npm run test

after_success:
  - docker push stono/asksarge
